version: '3.7'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインがmysql8からcaching_sha2_passwordになっているので変更する。
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" # コンテナ側:ホスト側
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.develop
    command: sh -c "yarn start"
    volumes:
      - ./frontend:/usr/src/datecourses
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.develop
    environment:
      FRONTEND_DOMAIN: http://localhost:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 7777 -b '0.0.0.0'"
    volumes:
      - ./backend:/date-course-api:cached # カレントディレクトリを/date-course-apiにバインドマウントしている
    ports:
      - 7777:7777
    depends_on:
      - db
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    # command: npx cypress open
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
volumes:
  mysql-data:
