version: '3.7'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインがmysql8からcaching_sha2_passwordになっているので変更する。
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/date_course # カレントディレクトリを/date_courseにバインドマウントしている
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
      - log-data:/date_course/log
    depends_on:
      db: # dbサーバーに依存する
        condition: service_started #dbコンテナが起動してから起動する
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要

  nginx:
    build: nginx/
    volumes:
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
    ports:
      - 80:80
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
