version: '3.7'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # コンテナ側:ホスト側
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインがmysql8からcaching_sha2_passwordになっているので変更する。
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/date_course # カレントディレクトリを/date_courseにバインドマウントしている
    ports:
      - 3000:3000
    depends_on:
      db: # dbサーバーに依存する
        condition: service_started #dbコンテナが起動してから起動する
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要
    # environment:
    #   WEBPACKER_DEV_SERVER_HOST: frontend
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.development
  #   # webpack-dev-serverを起動
  #   command: bash -c "./node_modules/.bin/webpack-dev-server --config config/webpack/development --host 0.0.0.0 --port 3035"
volumes:
  mysql-data:
