version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/date_course # カレントディレクトリを/date_courseにバインドマウントしている
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
      - log-data:/date_course/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要
    command: bash -c "bundle exec puma -C config/puma.rb -e production"
  nginx:
    build: 
      context: containers/nginx
    volumes:
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
