version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/date-course # カレントディレクトリを/date-courseにバインドマウントしている
      - public-data:/date-course/public
      - tmp-data:/date-course/tmp
      - log-data:/date-course/log
    ports:
      - "3000:3000"
    command: bash -c "bundle exec puma -C config/puma.rb -e production"
  nginx:
    build: 
      context: containers/nginx
    volumes:
      - public-data:/date-course/public
      - tmp-data:/date-course/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
