version: '3.7'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインがmysql8からcaching_sha2_passwordになっているので変更する。
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" # コンテナ側:ホスト側
  frontend:
    build:
      context: ./frontend
    environment:
      GoogleMapApiKey: ${GoogleMapApiKey}
    command: sh -c "yarn start && yarn install" #E2Eテストのためにcypress installが必要
    volumes:
      - ./frontend:/usr/src/datecourses

    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend/date-course-api # カレントディレクトリを/date-course-apiにバインドマウントしている
    ports:
      - 7777:3000
    depends_on:
      - db
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要
volumes:
  mysql-data:
