version: '3.7'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: ${DATE_COURSE_DATABASE_NAME}
      MYSQL_USER: ${DATE_COURSE_DATABASE_USER}
      MYSQL_PASSWORD: ${DATE_COURSE_DATABASE_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインがmysql8からcaching_sha2_passwordになっているので変更する。
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/date_course # カレントディレクトリを/date_courseにバインドマウントしている
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
      - log-data:/date_course/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true # binding.pryをdockerの環境でするために必要
    stdin_open: true # binding.pryをdockerの環境でするために必要
    command: bash -c "bundle exec puma -C config/puma.rb -e production"
  nginx:
    build: 
      context: containers/nginx
    volumes:
      - public-data:/date_course/public
      - tmp-data:/date_course/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
