source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'
# 住所やカテゴリのmodelデータに使用する。変更される可能性が低いものをハッシュとして管理できる
gem 'active_hash'
# Use Active Storage variant

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# 検索機能実装
gem 'ransack'

# アセットをS3パケットに同期できるようにする。
gem 'asset_sync'

# AWSの連携に必要なクラウドサービス
gem 'fog-aws'

# 住所から緯度と経度を取得するGemを実装
gem 'geocoder'

# 同一生成元ポリシー (Same-Origin Policy)」というポリシーによって設けられた制限を緩める(JavaScript で自由にやりとりできるところは、その JavaScript をとってきたところと同一の場所だけに制限する)
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
  gem 'factory_bot_rails'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'


  # 静的解析ツール
  # コミット時に指導でrubocopを走らせる
  gem 'pre-commit'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'

  # Capistranoに必要なgemをinstall
  gem 'capistrano', '~> 3.15'
end

# group :test do
#   # rspecの際に使用してきました。
#   gem 'launchy'
#   gem 'capybara'
#   gem 'selenium-webdriver'
# end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'pry-rails'
