name: Test
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: set plugin
        run: |
          docker-compose down --volumes
          docker-compose up -d --build
          mysql -h 127.0.0.1 --port 3306 -u root -password -e "$(cat $(find ./ -name hoge.sql))"