name: Test
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options:
          -e MYSQL_ROOT_PASSWORD=password --entrypoint sh mysql:8.0.23 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    container:
      image: ruby:2.7.2
    steps:
      - uses: actions/checkout@v2
      - name: setup bundle
        run: |
          gem install bundler
          bundle install
      - name: setup yarn
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          npm install -g yarn
          yarn install
      - name: setup migrate
        run: |
          rails db:create
          rails db:migrate
      - name: run spec
        run: bundle exec rspec spec
