name: Test
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.23
        volumes:
          - mysqlconfd:/etc/mysql/conf.d
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=root -e MYSQL_DATABASE=db --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    container:
      image: ruby:2.7.2
    steps:
      - uses: actions/checkout@v2
      - name: setup bundle
        run: |
          bundle install
      - name: setup yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - 
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list 
      - name: setup nodejs
        run: |
          apt-get update -qq 
          apt-get install -y nodejs yarn
      - name: setup seed
        run: |
          rails db:create
          rails db:migrate
          rails db:seed 
      - name: run spec
        run: bundle exec rspec spec     