name: Test
on:
  pull_request:
    branches:
      - master
    types: [closed]
env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  backend_test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options:
          -e MYSQL_ROOT_PASSWORD=password --entrypoint sh mysql:8.0.23 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    container:
      image: ruby:3.0.3
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          apt-get update -qq
          apt-get install -y build-essential libpq-dev nodejs
          cd backend
          gem install bundler
          bundle install
      - name: setup migrate
        run: |
          rails db:create
          rails db:migrate
          rails db:seed
      - name: run rubocop
        run: rubocop --fail-level W --display-only-fail-level-offenses
      - name: run rspec
        run: rspec spec
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Frontend App
        run: |
          cd frontend
          yarn install
          yarn build
          yarn start
      - uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:3000"
          working-directory: ../e2e



