name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose run web yarn install --check-files
        docker-compose run web yarn upgrade
        # イメージのビルド
        docker-compose build
        # データベースの作成
        docker-compose exec web rails db:create
        docker-compose exec web rails db:migrate
        docker-compose exec web rails db:seed
      env:
        RAILS_ENV: test

    - name: Run RSpec
      shell: bash
      run:  |
        docker-compose run web bundle exec rspec
      env:
        RAILS_ENV: test